# Generated by Django 3.2.12 on 2022-05-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_topic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='approval',
            field=models.BooleanField(default=False, verbose_name='承認'),
        ),
    ]
